version: '2'

services:

  web:
    build: .
    command: bundle exec foreman start -f Procfile.development
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'

  postgresData:
    image: busybox
    command:
      - "true"
    volumes:
      - /var/lib/postgresql/data

  postgres:
    build: dbcontainer
    environment:
      POSTGRES_PASSWORD: asecurepassword
      DB_PASSWORD: secret
    volumes_from:
      - postgresData

  redis:
    image: redis

  memcached:
    image: memcached
