development:
  associate_tag: "mamajamas-20"
  access_key_id: "AKIAIXAEIBVZBZEU56MQ"
  secret_key: "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"
  bucket: "mamajamas-dev"
test:
  associate_tag: "mamajamas-20"
  access_key_id: "AKIAIXAEIBVZBZEU56MQ"
  secret_key: "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"
  bucket: "mamajamas-test"
staging:
  associate_tag: "mamajamas-20"
  access_key_id: "AKIAIXAEIBVZBZEU56MQ"
  secret_key: "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"
  bucket: "mamajamas"
production:
  associate_tag: "mamajamas-20"
  access_key_id: "AKIAIXAEIBVZBZEU56MQ"
  secret_key: "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"
  bucket: "mamajamas"
